config/routes.rb
Rails.application.routes.draw do

  get 'search/index'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: "home#index"
  get 'home/index'

  get 'search' => 'search#index'

  resources :posts, only: [:new, :create, :destroy] do
    resources :likes, :comments, :only => [:create, :index, :new, :destroy]
  end
  resources :comments, :only => [:destroy, :show, :edit, :update]
  resources :likes, :only => [:destroy, :show, :create]
  resources :users, only: [:show, :edit, :update]
  # resources :posts, only: [:new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/hash_tag.rb
class HashTag < ApplicationRecord
  has_many :post_hash_tags
  has_many :posts, through: :post_hash_tags
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  after_commit :create_hash_tags, on: :create

  belongs_to :user

  has_one_attached :image
  validate :image_presence

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :post_hash_tags
  has_many :hash_tags, through: :post_hash_tags

  def image_presence
    errors.add(:image, "can't be blank") unless image.attached?
  end

  def extract_name_hash_tags
    description.to_s.scan(/#\w+/).map{|name| name.gsub("#", "")}
  end

  def create_hash_tags
    extract_name_hash_tags.each do |name|
      hash_tags.create(name: name)
    end
  end

end

app/models/post_hash_tag.rb
class PostHashTag < ApplicationRecord
  belongs_to :post
  belongs_to :hash_tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_one_attached :avatar

  mount_uploader :avatar, AvatarUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :password, :password_confirmations])
  end

  def after_sign_in_path_for(_resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(_resource)
    new_user_session_path
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.all
  end

  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :comment, :username, :user_id))
    @comment.user_id = current_user.id
    @comment.username = current_user.username
    @comment.save!
    redirect_to root_path
  end

  def destroy
    @post = Post.find(params[:post_id])
    Comment.find_by(post_id: params[:post_id]).destroy
    redirect_to root_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.order(created_at: :desc).page(params[:page]).per(5)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @like = Like.create({ user_id: current_user.id, post_id: params[:post_id] })
    redirect_to root_path
  end

  def destroy
    @post = Post.find(params[:post_id])
    Like.find_by(user_id: current_user.id, post_id: params[:post_id]).destroy
    redirect_to root_path
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new

  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = Comment.where(post_id: params[:id])
  end

  def create
    Post.create(post_params)
    redirect_to root_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:description, :image, :user_id)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if params[:query].start_with?('#')
      query  = params[:query].gsub('#', '')
      @posts = Post.joins(:hash_tags).where(hash_tags: {name:    query})
    else
      @posts = Post.where("description like ?", "%#{params[:query]}%")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def new

  end

  def create
    User.create(user_params)

    redirect_to root_path
  end

  def show
    @user  = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    current_user.update(user_params)
    redirect_to current_user
  end

  def destroy
    User.find(session[:user_id]).destroy
    session[:user_id] = nil
    redirect_back(fallback_location: root_path)
  end

  private

  def user_params
    params.require(:user).permit(:username, :name, :website, :bio, :email, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title> Imago </title>
  </head>
  <body>

    <div class="col-lg-8 col-md-12 mb-lg-0 mb-4">
      <div class="card testimonial-card">
        <div class="card-up info-color"></div>
        <div class="card-body">
          <h4> New Imago: </h4>
          <hr>
          <h6> add a description: </h6>
          <%= form_for Post.new do |f| %>
          <div class="form-group">
            <%= f.text_field :description %>
          </div>

          <div class="form-group">
            <%= f.file_field :image, class: 'btn btn-light' %>
          </div>

          <div class="form-group">
            <%= f.text_field :user_id, value: current_user.id, class:'d-none'%>
          </div>
          <br>
          <div class="text-center">
            <%= f.submit 'Post', class: 'btn btn-light' %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
    <hr>
    <br>
    <div class="posts">
      <% @posts.each do |post| %>
      <section class="post">
        <div class="user">
          <div class="avatar">
            <%= link_to image_tag('placeholder.png') %>
               <%# <%= image_tag current_user.avatar.url, :size => "40x30" %>
          </div>
          <div class="username">
            <h4><%= post.user.username %></h4>
          </div>

        </div>
        <%= image_tag post.image, class: 'main-image' %>
        <div class="description">
          <% post.description.to_s.split(' ').each do |word| %>
            <% if word.start_with?('#') %>
              <%= link_to word, search_path(query: word) %>
            <%else %>
              <%= word %>
            <%end %>
          <% end %>
          <hr>
          Posted at: <%= post.created_at.strftime("%H:%M on %d-%m-%Y") %>
          <hr>
          <% pre_like = Like.find_by(user_id: current_user.id, post_id: post) %>
          <% if pre_like %>
            <%= link_to image_tag('thumb_down.png', :size => "20x20", alt: "unlike imago"), post_like_path(post, pre_like), method: :delete %>(<%= post.likes.count %>)
          <% else %>
            <%= link_to image_tag('like_thumb.png', :size => "20x20", alt: "like imago"), post_likes_path(post), method: :post %>(<%= post.likes.count %>)
          <% end %>
          <% if current_user.id == post.user_id %>
          <%= link_to image_tag('delete.png', :size => "20x20"), post_path(post), method: :delete %>
         <% end %>
        </div>

        <hr>
        <a class="btn btn-light" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
          See Comments
        </a>
        <br><br>
        <% post.comments.each do |comment| %>
        <div class="collapse" id="collapseExample">
          <div class="card card-body">
            <ul class="list-group">
              <li class="list-group-item">"<%= comment.comment %>"
                <div class="d-flex w-100 justify-content-between">
                  <small class="text-muted"> Comment by: <%= comment.username %></small>
                  
                </div>
              </li>
            </ul>
          </div>
        </div>
        <% end %>
        <%= form_with(model: [ post, post.comments.build ], local: true) do |form| %>
        <p>
          <%= form.label :Leave_a_comment %><br>
          <%= form.text_field :comment %>
        </p>
        <p>
          <%= form.submit 'Comment', class: 'btn btn-light' %>
        </p>
        <% end %>
        </section>
        <% end %>
      </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Imago </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!--Nav Bar-->
    <nav class="navbar navbar-light bg-light d-flex">
      <font face="courier new"
      <div class="container">
        <div class="logo">
          <a class="navbar-brand" href="/">

            <%= fa_stacked_icon "eye" %>
            Imago
          </a>
        </div>
        <div class="m-auto">
          <%= form_with url: search_path, method: :get, local: true, class: 'form-inline search-form' do |form| %>
            <%= form.text_field :query, value: params[:query], class: 'form-control mr-sm-2', placeholder: 'search by #' %>
          <% end %>
        </div>
        <div class="user-section">

          <% if user_signed_in? %>
          <a href="/">
            <i class="fa fa-home" aria-hidden="true"></i>
          </a>
          <a href="<%= user_path(current_user) %>">
            <i class="fa fa-user"></i>
          </a>
          <a href="<%= destroy_user_session_path method: :delete %>">
            <i class="fa fa-sign-out"></i>
          </a>
          <% else %>
          <a href="<%= new_user_session_path %>">
            <i class="fa fa-sign-in"></i>
          </a>
          <% end %>
        </div>
      </div>
      </font>
    </nav>
    <font face="courier new">
    <center>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </center>
    </font>

    <main class="container" style="min-height: 500px;">
      <font face="courier new">
      <center>
      <%= yield %>
      </center>
      </font>
    </main>

    <!--Footer-->
    <footer class="container footer">
      <hr>
      <nav class="navbar d-flex">
        <font face="courier new">
        <ul>
          <a style="text-decoration:none;" target="blank" href="https://github.com/cesarecamurani">
            <h6>ABOUT CESARE</h6>
          </a>
        </ul>
        </font>
        <font face="courier new">
        <p> © 2019 Imago - Powered by Cesare on Rails </p>
        </font>
      </nav>
    </footer>
  </body>
</html>

app/views/search/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title> Search Results </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="search-page">
      <% if @posts.exists? %>
        <h4> Results of your search: </h4>
      <% else %>
        <h4> Oops! No matching Imago ... </h4>
        <hr>
        <img src="https://cdn-images-1.medium.com/max/780/1*8-fgvBPAFgPpbbr-YwD9Xw.jpeg">
        <hr>
      <% end %>
      <div class="posts">
        <% @posts.each do |post| %>
        <section class="post">
          <div class="user">
            <div class="avatar">
              <%= image_tag('placeholder.png', :class => "rounded-circle img-fluid") %>
                <%# <%= current_user.avatar.url %>
            </div>
            <div class="username">
              <h4><%= post.user.username %></h4>
            </div>

          </div>
          <%= image_tag post.image, class: 'main-image' %>
          <div class="description">
            <% post.description.to_s.split(' ').each do |word| %>
              <% if word.start_with?('#') %>
                <%= link_to word, search_path(query: word) %>
              <%else %>
                <%= word %>
              <%end %>
            <% end %>
            <hr>
            Posted at: <%= post.created_at.strftime("%H:%M on %d-%m-%Y") %>

          </div>
          </section>
          <% end %>
        </div>
    </div>
  </body>
</html>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title> Imago Edit Profile </title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
      
      <div class="details tab-content">
        <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
          <%= form_with model: current_user, local: true, html: {class: "form-horizontal form-edit-user"} do |f| %>
        <div class="form-group row">
          <div class="col-sm-3 col-form-label">
            <%# <%= image_tag current_user.avatar.url, :class => "rounded-circle img-fluid", :size => "200x200" %>
          </div>
          <div class="col-sm-8">

            <h2> <%= current_user.username %> </h2>

          </div>
        </div>
        <div class="form-group row">
          <%= f.label :avatar, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.file_field :avatar, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :name, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :name, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :username, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :username, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :bio, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_area :bio, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :website, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :website, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :email, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :email, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-sm-3">
          </div>
          <div class="col-sm-9">
            <%= f.submit "Save Changes", class: 'btn btn-light'%>
          </div>
        </div>
        <% end %>
        </div>
      </div>

  </body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <title> Imago My Page </title>
  </head>
  <body>
    <h2> <%= current_user.username %> </h2>
    <br>
    <div class="col-lg-4 col-md-12 mb-lg-0 mb-4">
        <div class="card testimonial-card">
          <div class="card-up info-color"></div>
          <div class="avatar mx-auto white">
            <br>
             <%# <%= image_tag current_user.avatar.url, :class => "rounded-circle img-fluid", :size => "200x200" %>
            <%= image_tag('placeholder.png', :class => "rounded-circle img-fluid") %>
          </div>
          <div class="card-body">
            <h6> Intro: </h6>
            <h4 class="bio"> <%= current_user.bio %> </h4>
            <hr>
            <center>
              <p>
              <span><b> <%= @posts.count %> </b></span> posts <br>
              <span><b> 0 </b></span> followers <br>
              <span><b> 0 </b></span> following
              </p>
            <hr>
            </center>
            <h4 class="name"> <%= current_user.name %> </h4>
            <a class="website"> <%= current_user.email %> </a>
            <hr>
            <a class="edit-profile" href="<%= edit_user_path(@user) %>">
              <button type="button" class="btn btn-light"> Edit Profile </button>
            </a>
          </div>
        </div>
      </div>
      <hr>
      <div class="posts">
        <% @posts.each do |post| %>
        <section class="post">
          <div class="user">
            <div class="avatar">
              <!-- <img src="https://image.ibb.co/hPKoao/penny.jpg"> -->
              <%= image_tag('placeholder.png', :class => "rounded-circle img-fluid") %>
            </div>
            <div class="username">
              <h4><%= post.user.username %></h4>
            </div>

          </div>
          <%= image_tag post.image, class: 'main-image' %>
          <div class="description">
            <% post.description.to_s.split(' ').each do |word| %>
              <% if word.start_with?('#') %>
                <%= link_to word, search_path(query: word) %>
              <%else %>
                <%= word %>
              <%end %>
            <% end %>
            <hr>
            Posted at: <%= post.created_at.strftime("%H:%M on %d-%m-%Y") %>

            <hr>
            <% pre_like = Like.find_by(user_id: current_user.id, post_id: post) %>
            <% if pre_like %>
              <%= link_to image_tag('thumb_down.png', :size => "20x20", alt: "unlike imago"), post_like_path(post, pre_like), method: :delete %>(<%= post.likes.count %>)
            <% else %>
              <%= link_to image_tag('like_thumb.png', :size => "20x20", alt: "like imago"), post_likes_path(post), method: :post %>(<%= post.likes.count %>)
            <% end %>
            <%= link_to image_tag('delete.png', :size => "20x20", alt: "delete imago"), post_path(post), method: :delete %>
          </div>
          <hr>
          <% post.comments.each do |comment| %>

              <ul class="list-group">
                <li class="list-group-item">"<%= comment.comment %>"
                  <div class="d-flex w-100 justify-content-between">
                    <small class="text-muted"> Comment by: <%= comment.username %></small>
                  </div>
                </li>
              </ul>

          <% end %>
          </section>
          <% end %>
        </div>
      <hr>
  </body>
</html>